sudo: false
language: ruby
cache:
  bundler: true
  directories:
    - $(npm root)
    - ~/bin
rvm:
  - '1.8.7-p371'
  - '1.9.3-p551'
  - '2.0.0-p648'
  - '2.1.10'
  - '2.2.8'
  - '2.3.5'
  - '2.4.2'
  - 'jruby-9.0.5.0'
  - 'jruby-9.1.9.0'
script:
  - bundle exec image_optim --info
  - bundle exec rspec
before_install:
  - gem update --system
  - gem update bundler
  - nvm install stable
  - mkdir -p ~/bin
  - command -v svgo || npm install -g svgo
  - command -v pngout || curl -L "http://static.jonof.id.au/dl/kenutils/pngout-20130221-linux.tar.gz" | tar -xz -C ~/bin --strip-components 2 --wildcards '*/x86_64/pngout'
matrix:
  include:
    - env: CODECLIMATE=✓
      rvm: '2.4.2'
      after_success: bundle exec codeclimate-test-reporter
    - env: RUBOCOP=✓
      rvm: '2.4.2'
      script: bundle exec rubocop
      before_install:
    - env: CHECK_RUBIES=✓
      rvm: '2.4.2'
      script: bundle exec travis_check_rubies
      before_install:
addons:
  code_climate:
    repo_token:
      secure: FDikT3JnOJHOAFSaKwVPB1VOphU0sSzAnzQ+YjSt9XFE+9uFQHth/j4rFoVoqALhCj+47trv6spwkbcSjGCVzm+87OI80GkLCCzNjDOz2W4sP9JWItVgS1VoWW+ioPxpLgpguTb3wutwKOUMEAf+40EX657ZiHumM7nNHrF+RCU=
