language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - '2.0'
  - '2.1'
  - '2.2'
  - jruby-18mode
  - jruby-19mode
  - ree
script:
  if [ -n "$RUBOCOP" ]; then
    bundle exec rubocop
  ; elif [ -n "$RAILS_VERSION" ]; then
    bundle exec image_optim --info
    && bundle exec rspec spec/image_optim/railtie_spec.rb
  ; else
    bundle exec image_optim --info
    && bundle exec rspec
  ; fi
before_install:
  if [ -z "$RUBOCOP" ]; then
    mkdir ~/bin
    && npm install -g svgo
    && curl -L "http://static.jonof.id.au/dl/kenutils/pngout-20130221-linux.tar.gz" | tar -xz -C ~/bin --strip-components 2 --wildcards '*/x86_64/pngout'
  ; fi
env:
  - PATH=~/bin:$PATH
matrix:
  fast_finish: true
  allow_failures:
    - rvm: '2.2'
  include:
    - env: RAILS_VERSION='~> 3.2'
      rvm: default
    - env: RAILS_VERSION='~> 4.0'
      rvm: default
    - env: RUBOCOP=true
      rvm: default
addons:
  code_climate:
    repo_token:
      secure: FDikT3JnOJHOAFSaKwVPB1VOphU0sSzAnzQ+YjSt9XFE+9uFQHth/j4rFoVoqALhCj+47trv6spwkbcSjGCVzm+87OI80GkLCCzNjDOz2W4sP9JWItVgS1VoWW+ioPxpLgpguTb3wutwKOUMEAf+40EX657ZiHumM7nNHrF+RCU=
