language:
  - ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - ree
script: bundle exec rspec
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq advancecomp gifsicle jhead jpegoptim libjpeg-progs optipng pngcrush
  - wget http://static.jonof.id.au/dl/kenutils/pngout-20130221-linux.tar.gz
  - tar -xzf pngout-*-linux.tar.gz
  - mv pngout-*-linux pngout-linux
env:
  - PATH=pngout-linux/x86_64:$PATH
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
